spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO}
    show-sql: ${DATABASE_SHOW_SQL}
    properties:
      hibernate:
        validator:
          apply_to_ddl: ${DATABASE_APPLY_VALIDATOR}
        format_sql: ${DATABASE_FORMAT_SQL}
        dialect: ${DATABASE_DIALECT}
  flyway:
    enabled: ${FLYWAY_ENABLED}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE}
    locations: ${FLYWAY_LOCATIONS}
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port: ${SERVER_PORT}

jwt:
  algorithm: ${JWT_ALGORITHM}
  secret: ${JWT_SECRET}
  expireAt: ${JWT_EXPIRE_AT}

angular:
  cors:
    allowed-origins: ${ANGULAR_ALLOWED_ORIGINS}

app:
  books:
    directory: /books
  images:
    directory: /images